### ISSUE TITLE
パスを平仮名にしても、yubimoji_recognize.pyで読み込める方法

### ISSUE THREAD

**Issue by kappakun17** [hello-deaf-world/Yubimoji_Recgnizer#7]
@KagenoMoheji 
タイトルどおりですが、パスを平仮名にすると、写真がyubimoji_recognize.pyで読み込めなくなります。

branch : [feature_mediapipe_get_num_ren-edit](https://github.com/hello-deaf-world/Yubimoji_Recgnizer/tree/feature_mediapipe_get_num_ren-edit)

背景
- Japanese_list.pyに入っていたローマ字を全部平仮名に変更
- `pipenv run py yubimoji_recognize.py`で実行するも、読み込めなかった
- 試しに、image.pyでファイルの読み込みをプリントすると以下の実行結果が出た

> `['D:\\Hello_Deaf_World\\pro-yubimoji-_recognizer\\Github\\Yubimoji_Recgnizer\\yubimoji_recognizer\\src/images\\0.あ\\あ.png', 'D:\\Hello_Deaf_World\\pro-yubimoji-_recognizer\\Github\\Yubimoji_Recgnizer\\yubimoji_recognizer\\src/images\\1.い\\い.png', 'D:\\Hello_Deaf_World\\pro-yubimoji-_recognizer\\Github\\Yubimoji_Recgnizer\\yubimoji_recognizer\\src/images\\2.う\\う.png', 'D:\\Hello_Deaf_World\\pro-yubimoji-_recognizer\\Github\\Yubimoji_Recgnizer\\yubimoji_recognizer\\src/images\\3.え\\え.png', 'D:\\Hello_Deaf_World\\pro-yubimoji-_recognizer\\Github\\Yubimoji_Recgnizer\\yubimoji_recognizer\\src/images\\4.お\\お.png']`

- 以上の結果からパスが作成できていることが確認できた
- 試しにJapanese_list.pyの最初にある「あ」だけ"a"に変更してトライしてみた
- 実行結果、a.pngのみ写真を読み込むことができた

解決方法
やはり、Japanese_list.pyをローマ字で登録する以外ないのでは・・・
もし日本語のパスで読み込む方法があれば、教えてほしいです。

**Comment by KagenoMoheji** [comment]
@kappakun17 
OpenCVのファイル操作関数では日本語名読み込めないみたいね．
ローマ字にしよか，そもそも日本語ディレクトリとか好ましくないしな…
- [日本語pathのファイルをopenCVが読んでくれないのでPILで読んでから渡した](https://qiita.com/studio_haneya/items/204b83df29110e1d909e)

**Comment by kappakun17** [comment]
@KagenoMoheji 

了解！
平仮名表記止めます！
いい勉強になったわ✊
